name: Build

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  schedule:
    # runs the CI everyday at 10AM
    - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel:
          - stable

    steps:
      - uses: actions/checkout@v3.1.0
        
      - uses: subosito/flutter-action@v2.7.1
        with:
          channel: ${{ matrix.channel }}

      - name: Add pub cache bin to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Add pub cache to PATH
        run: echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV

      - run: dart pub global activate melos
        
      - name: Install dependencies
        run: melos bootstrap --ignore "codemod_riverpod_*,riverpod_cli" 

      - name: Check format
        run: melos exec --ignore="website_snippets" -- "flutter format --set-exit-if-changed ."

      - name: Generate
        run: melos exec --depends-on="build_runner" -- "dart run build_runner build --delete-conflicting-outputs"

      - name: Analyze
        run: melos exec --ignore="codemod_riverpod_test*,riverpod_lint_flutter_test" -- "flutter analyze"

      - name: Run tests
        run: melos run test

      - name: Upload coverage to codecov
        # only relevant for repo owner
        if: ${{ github.repository_owner }} == 'rrousselGit'
        run: curl -s https://codecov.io/bash | bash